# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-24 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_auto_20180123_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageupload',
            old_name='uploaduser',
            new_name='user',
        ),
        migrations.AddField(
            model_name='imageupload',
            name='username',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
