# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-24 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0006_auto_20180124_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
