# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-24 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0007_auto_20180124_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='image',
            field=models.FileField(upload_to='images/%Y/%M/%D'),
        ),
    ]
