# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-24 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0008_auto_20180124_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='image',
            field=models.FileField(upload_to='upload_image'),
        ),
    ]
