# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-24 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0010_auto_20180124_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='image',
            field=models.ImageField(upload_to='upload_image/'),
        ),
    ]
