# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-25 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0012_auto_20180124_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='like',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='user_like',
            field=models.IntegerField(null=True),
        ),
    ]
