# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-12 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0013_auto_20180125_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='slug',
            field=models.CharField(default=models.CharField(max_length=100), max_length=40),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='user_like',
            field=models.IntegerField(blank=True, verbose_name='auth.User'),
        ),
    ]
