# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-12 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0014_auto_20180212_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='slug',
            field=models.CharField(max_length=50),
        ),
    ]
