# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-12 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0015_auto_20180212_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageupload',
            old_name='user_like',
            new_name='users_like',
        ),
    ]
