# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-12 15:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upload', '0016_auto_20180212_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageupload',
            name='like',
        ),
        migrations.RemoveField(
            model_name='imageupload',
            name='users_like',
        ),
        migrations.AddField(
            model_name='imageupload',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='images_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
